// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw_stAIrqOlU2ZtbAPryrKX5YEj5k553Y',
    appId: '1:1038064506820:web:69a5e01754508af0ea7691',
    messagingSenderId: '1038064506820',
    projectId: 'camexplore-f3123',
    authDomain: 'camexplore-f3123.firebaseapp.com',
    storageBucket: 'camexplore-f3123.firebasestorage.app',
    measurementId: 'G-8REFBPE9VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2TbMwIjHnK6UNuflNTwaGg2zf3X0ncIc',
    appId: '1:1038064506820:android:7f00dae76edb2acfea7691',
    messagingSenderId: '1038064506820',
    projectId: 'camexplore-f3123',
    storageBucket: 'camexplore-f3123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPncyMO4Ds4lQq1hwVqkoA7dOuhpxn3Tw',
    appId: '1:1038064506820:ios:a679ad996b173f58ea7691',
    messagingSenderId: '1038064506820',
    projectId: 'camexplore-f3123',
    storageBucket: 'camexplore-f3123.firebasestorage.app',
    androidClientId: '1038064506820-kfjne0oj2m53hqv9h6cpcgqkq8glndr6.apps.googleusercontent.com',
    iosClientId: '1038064506820-3qp0atvhrq8v9utsj6vn5ighl70qofji.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPncyMO4Ds4lQq1hwVqkoA7dOuhpxn3Tw',
    appId: '1:1038064506820:ios:a679ad996b173f58ea7691',
    messagingSenderId: '1038064506820',
    projectId: 'camexplore-f3123',
    storageBucket: 'camexplore-f3123.firebasestorage.app',
    androidClientId: '1038064506820-kfjne0oj2m53hqv9h6cpcgqkq8glndr6.apps.googleusercontent.com',
    iosClientId: '1038064506820-3qp0atvhrq8v9utsj6vn5ighl70qofji.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw_stAIrqOlU2ZtbAPryrKX5YEj5k553Y',
    appId: '1:1038064506820:web:28fb182f690a747dea7691',
    messagingSenderId: '1038064506820',
    projectId: 'camexplore-f3123',
    authDomain: 'camexplore-f3123.firebaseapp.com',
    storageBucket: 'camexplore-f3123.firebasestorage.app',
    measurementId: 'G-0HWPJNJ6K4',
  );
}
